@startuml
class Robot {
  - room_assigned: string
  - task_assigned: string
  - robot_status: string
  - timer: int
  
  + clean_room(): void
  + go_home(): void
  + get_robot_status(): string
  + update_robot_status(): string
}

interface CommandLine {}

Management "1" o--> "0...n" Rooms
Management "1" *--> "0...n" Robot
Robot "1" o--> "1" Rooms
Management ..|> CommandLine
@enduml