@startuml
class Room {
    - room_name:    String
    - estimated_clean_time: int
    - room_status:  Status
    - room_size:    Size
    + get_estimated_clean_time(): int
    + update_room_status(): void
    + status_to_string():   String
    + size_to_string():     String
    + time_to_string():     String
    + to_string():          String
}

enum Status {
    Dirty
    In-progress
    Clean
}

enum Size {
    Small
    Medium
    Large
}

interface CommandLine {}

Management "1" o--> "0...n" Room
Management "1" *--> "0...n" Robot
Robot "1" o--> "1" Room
Room "1" *--> "1" Status
Room "1" *--> "1" Size
Management ..|> CommandLine
@enduml
