@startuml
!define RECTANGLE class

box #LightGreen
  participant CommandLine as CLI
end box

box #LightBlue
  participant Management as M
end box

box #Pink
  participant Robots as Bot
end box

box #LightYellow
  participant Rooms as R
end box

CLI -> M : add new bot
activate M
M -> Bot: initialize new bot object (name, size, type)
M->M: add new bot to free set
M --> CLI : bot added
deactivate M

CLI -> M : add new room
activate M
M -> R: initialize new room object (name, size, time to clean)
M->M: add new room to dirty set
M --> CLI : room added
deactivate M

@enduml